export const PAGE_SIZE = 50;

export const SUBCATEGORIES = {
  '2000': [
    { value: '2080', label: 'Films/WEB-DL' },
    { value: '2040', label: 'Films/HD' },
    { value: '2045', label: 'Films/UHD' },
    { value: '2050', label: 'Films/Blu-Ray' },
    { value: '2030', label: 'Films/SD' },
    { value: '2070', label: 'Films/DVD' },
    { value: '2060', label: 'Films/3D' },
    { value: '2010', label: 'Films/Étranger' },
    { value: '2020', label: 'Films/Autre' },
  ],
  '5000': [
    { value: '5010', label: 'TV/WEB-DL' },
    { value: '5040', label: 'TV/HD' },
    { value: '5045', label: 'TV/UHD' },
    { value: '5030', label: 'TV/SD' },
    { value: '5070', label: 'TV/Anime' },
    { value: '5060', label: 'TV/Sport' },
    { value: '5080', label: 'TV/Documentaire' },
    { value: '5020', label: 'TV/Étranger' },
    { value: '5050', label: 'TV/Autre' },
  ],
  '3000': [
    { value: '3040', label: 'Musique/Lossless' },
    { value: '3010', label: 'Musique/MP3' },
    { value: '3030', label: 'Musique/Audiobook' },
    { value: '3020', label: 'Musique/Vidéo' },
    { value: '3060', label: 'Musique/Étranger' },
    { value: '3050', label: 'Musique/Autre' },
  ],
  '7000': [
    { value: '7020', label: 'Livres/EBook' },
    { value: '7030', label: 'Livres/Comics' },
    { value: '7010', label: 'Livres/Magazines' },
    { value: '7040', label: 'Livres/Technique' },
    { value: '7060', label: 'Livres/Étranger' },
    { value: '7050', label: 'Livres/Autre' },
  ],
  '4000': [
    { value: '4050', label: 'PC/Jeux' },
    { value: '4010', label: 'PC/0day' },
    { value: '4020', label: 'PC/ISO' },
    { value: '4030', label: 'PC/Mac' },
    { value: '4060', label: 'PC/Phone-iOS' },
    { value: '4070', label: 'PC/Phone-Android' },
    { value: '4040', label: 'PC/Phone-Autre' },
  ],
  '1000': [
    { value: '1080', label: 'Console/PS3' },
    { value: '1180', label: 'Console/PS4' },
    { value: '1040', label: 'Console/Xbox' },
    { value: '1050', label: 'Console/Xbox 360' },
    { value: '1140', label: 'Console/Xbox One' },
    { value: '1030', label: 'Console/Wii' },
    { value: '1130', label: 'Console/Wii U' },
    { value: '1010', label: 'Console/NDS' },
    { value: '1110', label: 'Console/3DS' },
    { value: '1120', label: 'Console/PS Vita' },
    { value: '1090', label: 'Console/Autre' },
  ],
};

export const TORRENT_STATE_MAP = {
  uploading:          { fr: 'Envoi',          en: 'Uploading',    cls: 'high' },
  stalledUP:          { fr: 'Envoi',          en: 'Seeding',      cls: 'mid' },
  forcedUP:           { fr: 'Seeding (forcé)', en: 'Seeding (forced)', cls: 'high' },
  queuedUP:           { fr: 'Seeding (file)', en: 'Seeding (queued)', cls: 'mid' },
  checkingUP:         { fr: 'Vérification',   en: 'Checking',     cls: 'mid' },
  pausedUP:           { fr: 'Pausé (seed)',    en: 'Paused (seed)', cls: 'low' },
  downloading:        { fr: 'Téléchargement', en: 'Downloading',   cls: 'mid' },
  stalledDL:          { fr: 'DL (stall)',      en: 'DL (stall)',   cls: 'low' },
  forcedDL:           { fr: 'DL (forcé)',      en: 'DL (forced)',  cls: 'mid' },
  queuedDL:           { fr: 'DL (file)',       en: 'DL (queued)',  cls: 'low' },
  checkingDL:         { fr: 'Vérification',   en: 'Checking',     cls: 'mid' },
  pausedDL:           { fr: 'Pausé',          en: 'Paused',       cls: 'low' },
  metaDL:             { fr: 'Métadonnées',    en: 'Metadata',     cls: 'mid' },
  missingFiles:       { fr: 'Fichiers manquants', en: 'Missing files', cls: 'low' },
  error:              { fr: 'Erreur',         en: 'Error',        cls: 'low' },
  moving:             { fr: 'Déplacement',    en: 'Moving',       cls: 'mid' },
  allocating:         { fr: 'Allocation',     en: 'Allocating',   cls: 'mid' },
  checkingResumeData: { fr: 'Reprise',        en: 'Resuming',     cls: 'mid' },
  Seeding:            { fr: 'Envoi',          en: 'Seeding',      cls: 'high' },
  Downloading:        { fr: 'Téléchargement', en: 'Downloading',  cls: 'mid' },
  Paused:             { fr: 'Pausé',          en: 'Paused',       cls: 'low' },
  Queued:             { fr: 'En file',        en: 'Queued',       cls: 'low' },
  Checking:           { fr: 'Vérification',   en: 'Checking',     cls: 'mid' },
  Error:              { fr: 'Erreur',         en: 'Error',        cls: 'low' },
  Stopped:            { fr: 'Arrêté',         en: 'Stopped',      cls: 'low' },
  'Check queue':      { fr: 'File vérif.',    en: 'Check queue',  cls: 'low' },
  'DL queue':         { fr: 'File DL',        en: 'DL queue',     cls: 'low' },
  'Seed queue':       { fr: 'File seed',      en: 'Seed queue',   cls: 'low' },
};
