export const state = {
  currentLang: 'fr',
  appMode: 'search',
  baseUrl: '',
  apiKey: '',
  allIndexers: [],
  manualIndexers: JSON.parse(localStorage.getItem('manual_indexers') || '[]'),
  searchSelectedIds: new Set(),
  resultsT1: [],
  resultsT2: [],
  commonResults: [],
  uniqueT1Results: [],
  uniqueT2Results: [],
  multiSearchResults: [],
  currentTab: 'search',
  sortCol: null,
  sortDir: 'asc',
  currentPage: 0,
  sortPrimary: { col: null, dir: 'asc' },
  sortSecondary: { col: null, dir: 'asc' },
  searchHistory: JSON.parse(localStorage.getItem('search_history') || '[]'),
  watchlist: JSON.parse(localStorage.getItem('watchlist') || '[]'),
  indexerStats: JSON.parse(localStorage.getItem('indexer_stats') || '{}'),
  indexerCustomizations: JSON.parse(localStorage.getItem('indexer_customizations') || '{}'),
  torrentClientSettings: JSON.parse(localStorage.getItem('torrent_client_settings') || '{}'),
  torrentList: [],
  qbtSessionCookie: '',
  transmissionSessionId: '',
  torrentsSortCol: null,
  torrentsSortDir: 'desc',
};
